[package]
name = "catsay-tui"
version = "0.1.0"
authors = ["leo <leonardod.trimarchi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.11.2"